### ISSUE TITLE
zipfile.BadZipFile: Bad CRC-32 for file 'normals.npy'

### ISSUE THREAD

**Issue by leduo1** [xnowbzhao/sapcu#12]
您好，我在训练的过程中碰到了这种错误，可以请您指点一下吗？非常感谢！
Traceback (most recent call last):
  File "/home/ubuntu/wwj/sapcu-master/trainfd.py", line 78, in <module>
    for batch in train_loader:
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
zipfile.BadZipFile: Caught BadZipFile in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/wwj/sapcu-master/fd/datacore.py", line 84, in __getitem__
    data =tsf.GdataKNN(dict(self.fields[0].load(model_path), ** self.fields[1].load(model_path)))
  File "/home/ubuntu/wwj/sapcu-master/fd/field.py", line 58, in load
    normals = pointcloud_dict['normals'].astype(np.float32)
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/site-packages/numpy/lib/npyio.py", line 253, in __getitem__
    return format.read_array(bytes,
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/site-packages/numpy/lib/format.py", line 812, in read_array
    data = _read_bytes(fp, read_size, "array data")
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/site-packages/numpy/lib/format.py", line 947, in _read_bytes
    r = fp.read(size - len(data))
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/zipfile.py", line 924, in read
    data = self._read1(n)
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/zipfile.py", line 1014, in _read1
    self._update_crc(data)
  File "/home/ubuntu/anaconda3/envs/sapcu/lib/python3.9/zipfile.py", line 942, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'normals.npy'

**Comment by yanjiaqiqi** [comment]
您好，一模一样，请问您解决了吗
