### ISSUE TITLE
target.xyz not found

### ISSUE THREAD

**Issue by AlbertWYP** [xnowbzhao/sapcu#15]
=> Loading checkpoint from local file...
out/fd\model_best.pt
=> Loading checkpoint from local file...
processing test/cow.xyz
generate seedpoint
./dense 0.004 2048
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "generate.py", line 128, in <module>
    pointcloud = np.array(generator.upsample(cloud))
  File "D:\wyp\Point_cloud\sapcu-master\generation.py", line 40, in upsample
    pc = self.generateiopoint(data)
  File "D:\wyp\Point_cloud\sapcu-master\generation.py", line 55, in generateiopoint
    data2=np.loadtxt("target.xyz")
  File "D:\wyp\Anaconda3\envs\point\lib\site-packages\numpy\lib\npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "D:\wyp\Anaconda3\envs\point\lib\site-packages\numpy\lib\npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "D:\wyp\Anaconda3\envs\point\lib\site-packages\numpy\lib\_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "D:\wyp\Anaconda3\envs\point\lib\site-packages\numpy\lib\_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: target.xyz not found.
Hellow, can you give me a hand?

**Comment by AlbertWYP** [comment]
Thanks  solved！

**Comment by QWTforGithub** [comment]
> Thanks solved！

May I ask how you resolved it? I take "g++ -std=c++11 dense.cpp -O2 -o dense" command, but there is a question:
